### WARNING: this file is supported from Sysdig Agent 0.80.0
# apiVersion: extensions/v1beta1  # If you are in Kubernetes version 1.8 or less please use this line instead of the following one
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysdig-agent
  labels:
    app: sysdig-agent
spec:
  selector:
    matchLabels:
      app: sysdig-agent
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sysdig-agent
    spec:
      volumes:
      - name: modprobe-d
        hostPath:
          path: /etc/modprobe.d
      - name: dshm
        emptyDir:
          medium: Memory
      - name: dev-vol
        hostPath:
          path: /dev
      - name: proc-vol
        hostPath:
          path: /proc
      - name: boot-vol
        hostPath:
          path: /boot
      - name: lib-vol
        hostPath:
          path: /lib
      - name: lib64-vol
        hostPath:
          path: /lib64
      - name: usr-vol
        hostPath:
          path: /usr
      # Linux bench requires /var/lib, /var/log, /var/tmp and /var/run
      # We need to mount these subdirs seperately, i.e we can't simply mount /var, as
      # /var/run is symlinked to /run on the host, so we mount /run to /var/run in the agent.
      - name: vartmp-vol
        hostPath:
          path: /var/tmp
      - name: varlog-vol
        hostPath:
          path: /var/log
      - name: varlib-vol
        hostPath:
          path: /var/lib
      - name: run-vol
        hostPath:
          path: /var/run
      - name: home-vol
        hostPath:
          path: /home
      - name: bin-vol
        hostPath:
          path: /bin
      - name: sbin-vol
        hostPath:
          path: /sbin
      - name: tmp-vol
        hostPath:
          path: /tmp
      - name: etc-vol
        hostPath:
          path: /etc
      - name: sysdig-agent-config
        configMap:
          name: sysdig-agent
          optional: true
      - name: sysdig-agent-secrets
        secret:
          secretName: sysdig-agent
      hostNetwork: true
      hostPID: true
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      # The following line is necessary for RBAC
      serviceAccount: sysdig-agent
      terminationGracePeriodSeconds: 5
      initContainers:
      - name: sysdig-agent-kmodule
        image: sysdig/agent-kmodule
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 1000m
            memory: 384Mi
          limits:
            memory: 512Mi
        volumeMounts:
        - mountPath: /etc/modprobe.d
          name: modprobe-d
          readOnly: true
        - mountPath: /host/boot
          name: boot-vol
          readOnly: true
        - mountPath: /host/lib/modules
          name: modules-vol
          readOnly: true
        - mountPath: /host/usr
          name: usr-vol
          readOnly: true
      containers:
      - name: sysdig-agent
        # WARNING: the agent-slim release is currently dependent on the above
        # initContainer and thus only functions correctly in a kubernetes cluster 
        image: sysdig/agent-slim
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          # Resources needed are subjective to the actual workload.
          # Please refer to Sysdig Support for more info.
          requests:
            cpu: 600m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 1536Mi
        readinessProbe:
          exec:
            command: [ "test", "-e", "/opt/draios/logs/running" ]
          initialDelaySeconds: 10
        volumeMounts:
        - mountPath: /host/dev
          name: dev-vol
          readOnly: false
        - mountPath: /host/proc
          name: proc-vol
          readOnly: true
        - mountPath: /host/boot
          name: boot-vol
          readOnly: true
        - mountPath: /host/lib
          name: lib-vol
          readOnly: true
        - mountPath: /host/lib64
          name: lib64-vol
          readOnly: true
        - mountPath: /host/usr
          name: usr-vol
          readOnly: true
        - mountPath: /host/var/run
          name: run-vol
        - mountPath: /host/var/log
          name: varlog-vol
          readOnly: true
        - mountPath: /host/var/lib
          name: varlib-vol
          readOnly: true
        - mountPath: /host/var/tmp
          name: vartmp-vol
          readOnly: true
        - mountPath: /host/home
          name: home-vol
          readOnly: true
        - mountPath: /host/bin
          name: bin-vol
          readOnly: true
        - mountPath: /host/sbin
          name: sbin-vol
          readOnly: true
        - mountPath: /host/tmp
          name: tmp-vol
          readOnly: true
        - mountPath: /host/etc
          name: etc-vol
          readOnly: true
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /host/etc
          name: etc-vol
          readOnly: true
        - mountPath: /opt/draios/etc/kubernetes/config
          name: sysdig-agent-config
        - mountPath: /opt/draios/etc/kubernetes/secrets
          name: sysdig-agent-secrets
